variables:
  CLJ_CONFIG: "./config/ci"

stages:
  - build-and-test
  - release

.build:
  stage: build-and-test
  image: clojure:tools-deps-1.9.0.391-alpine
  tags:
    - docker
  before_script:
    - apk --update add make nodejs-npm
  script:
    - make compile
  cache:
    paths:
      - .m2/repository

.test:
  stage: build-and-test
  image: clojure:tools-deps-1.9.0.391-alpine
  tags:
    - docker
  before_script:
    - apk --update add make nodejs-npm yarn
    - yarn add websocket
  script:
    - make test
  cache:
    paths:
      - .m2/repository

release:
  stage: release
  image: maven:latest
  tags:
    - docker
  variables:
    MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  script:
    - make deploy
  #only:
  #  - master