variables:
  CLJ_CONFIG: "./config/ci"

cache:
  paths:
    - .m2/repository

stages:
  - build-and-test
  - release

build:
  stage: build-and-test
  image: clojure:tools-deps-1.9.0.391-alpine
  tags:
    - docker
  before_script:
    - apk --update add make nodejs-npm
  script:
    - make compile

test:
  stage: build-and-test
  image: clojure:tools-deps-1.9.0.391-alpine
  tags:
    - docker
  before_script:
    - apk --update add make nodejs-npm yarn
    - yarn add websocket
  script:
    - make test

release:
  stage: release
  image: maven:3-jdk-8-alpine
  tags:
    - docker
  variables:
    MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  before_script:
    - apk --update add make gettext git
  script:
    - export RELEASE_VERSION=$(git describe --tags)
    - '[[ "master" != $CI_COMMIT_REF_NAME ]] || export RELEASE_VERSION=${RELEASE_VERSION/-*/-SNAPSHOT}'
    - envsubst '${RELEASE_VERSION}' <pom.xml.template >pom.xml
    - make mvn-deploy
  only:
    - master
    - tags