stages:
  - build-and-test

build:
  stage: build-and-test
  image: clojure:tools-deps-1.9.0.391-alpine
  tags:
    - docker
  before_script:
    - apk --update add make nodejs-npm
    - echo '{:mvn/local-repo "./m2"}' > ~/.clojure/deps.edn
  script:
    - make compile
  cache:
    key: m2
    paths:
      - m2

test:
  stage: build-and-test
  image: clojure:tools-deps-1.9.0.391-alpine
  tags:
    - docker
  before_script:
    - apk --update add make nodejs-npm yarn
    - yarn add websocket
    - echo '{:mvn/local-repo "./m2"}' > ~/.clojure/deps.edn
  script:
    - make test
  cache:
    key: m2
    paths:
      - m2